import Foundation
import SwiftData

/// A price-change record generated by `PresetSync` (M5) when the remote presets.json
/// version reports a different amount than our cached version. Surfaces as a banner
/// on the relevant Subscription Detail screen, and (Pro only) as a push notification.
@Model
final class PriceChangeAlert {
    @Attribute(.unique) var id: UUID
    var presetId: String
    var planKey: String
    var oldAmount: Decimal
    var newAmount: Decimal
    var currency: String
    var effectiveDate: Date
    /// English message body.
    var messageEn: String
    /// Simplified Chinese message body.
    var messageZh: String
    /// `nil` until the user dismisses the banner.
    var seenAt: Date?
    var createdAt: Date

    init(
        id: UUID = UUID(),
        presetId: String,
        planKey: String,
        oldAmount: Decimal,
        newAmount: Decimal,
        currency: String,
        effectiveDate: Date,
        messageEn: String,
        messageZh: String,
        seenAt: Date? = nil,
        createdAt: Date = .now
    ) {
        self.id = id
        self.presetId = presetId
        self.planKey = planKey
        self.oldAmount = oldAmount
        self.newAmount = newAmount
        self.currency = currency
        self.effectiveDate = effectiveDate
        self.messageEn = messageEn
        self.messageZh = messageZh
        self.seenAt = seenAt
        self.createdAt = createdAt
    }
}
